language: groovy

env:
  global:
  #GEB_SAUCE_LABS_USER
  - secure: KtMDlvNor6uIvXfUmYacvL7I6lxbOhwF/FqH9eOO7IvLC+WPM5XQbxPctgZbxCebr/P8QxlyP7AD8myxVB7Gwt4ywPBx28BfsS3BWs5la3TgdZK+7bVK518Jy2V4xRM56QGwPXl3FrhOlgsrttcq5NHt8t43NduAdu0leyEPjgayfxzaKEAEx4JfNBcnCe9B5aguMqJa1k9ELQTX94E2pkpJl48z0s1v9q0ZPtJ5UXs3v1rRGb2yaToH43+T9GsV+7J1169xnklZYaAfXiRnQ8omoex5Eu4ag33zhuSwEtdt3yCL/Yp83UrLbNVIWk2E6qL7nWswGzg52C+1jXnoGiFOOH1GsTz2t8jaBCR2RHcngzA8KSMGpjfFXCvLq+3yd9v+z8By2oQP5bRyruq8Jdn9ujc+ZDC/dIkE/Uol+Id+DxpPmG0haXDeV7Xeu4fXExD3UjXonzGW74p1X+0zBGHeOenLzL7XmbiCQLj7ACztOlOcAo8vrC8oFDpoi1ypngeciBwbodtySc1Mj0Tr5Fk6uf+kjRXcWc/lfgR4Rh+LjmqKjCa6cTh9tGsNWGBjjPgLffQ/xVc18bp0cM3BhYnhyghNdmfhVMiH+xnAfL95xElFSyjVHgICYXFfiZ50OVcnGp5cJ3onlbJ8iRcg5v6apl0PeGkA/LZwWy8XjTU=
  #GEB_SAUCE_LABS_ACCESS_PASSWORD
  - secure: Gdo2iHbhLAlIkHv+rrtviylG94W/iyEUpKB1fQwshcAzl8Rf6dWMMXnUn4WpI0T9cTxJrwxk4MUGMplYF5mNyUHFoPpeMFFesii6QJPRJlnmrSBpLPzpjctS1yhCjXYbOgKa3bxvqo9pU0U4KKUjJTrfZaeAjw9VrjDXbO4O4EAbFIID9+7bV4dE0cZMFTN1ua3Oq6jPgeOn7eRDnVsfrMPjpEKnmj4zFlUxvVIItUb1s1XX0mBS2Wn4CACSGVB4mTdo23nwnkJv7bZ+UyLkV/KNDtsNnBShRYL0/znmnoInX0PoxHj6pONwPyaro5oU2DWAURJh4Pdf0MyqDaCE1wG5IsWhXeEnZaAD5LY5S+RTrlDj75EkpeUDUgcIm9HFdu01HZjCJ4K1ZjjbejVMOU0zP4EHAPMVanxcTgv1PcutGJS7ZqopNSs2m5E1Df4WjX26qR7L67IQd7IGqvTLsNxvQT/p8wVazg3d82B7ygQP+Rtx2qtRk8zMQsdz7aXtj15PfaoA1sbEBki8CRhXfwibyI8yB8W5QtyDNmqYr+wYd8qwXAwP+zQN1IqmfCK3K3MAGFR4XxEpyONuMdMEa15QfESCl8zeOpRU/VFVTxlm3awCpwfFRQdKkb6X/4tFArFydIqRimT6OZgHcXNhbFq8J7nyy2nkh9ZR66+rTng=

addons:
  sauce_connect: true

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/